### ISSUE TITLE
s-lint init 执行报错

### ISSUE THREAD

**Issue by ali-pay** [jd-antelope/s-lint#1]
```bash
node -v
 16.13.1

npm -v
 8.2.0

s-lint -V
 0.0.3
```

```javascript
...
🎉eslint初始化成功!
...
🎉stylelint初始化成功!
...
🎉commitlint初始化成功!

初始化成功!

D:\NodeJS\node_global\node_modules\selling-lint-cli\build\commands\init.js:29
        return safeDepList.includes(dep);
                           ^

TypeError: Cannot read properties of undefined (reading 'includes')
    at D:\NodeJS\node_global\node_modules\selling-lint-cli\build\commands\init.js:29:28
    at Array.filter (<anonymous>)
    at tryToRemovePackage (D:\NodeJS\node_global\node_modules\selling-lint-cli\build\commands\init.js:28:10)
    at checkAndRemoveOldPackage (D:\NodeJS\node_global\node_modules\selling-lint-cli\build\commands\init.js:49:36)
    at initLint (D:\NodeJS\node_global\node_modules\selling-lint-cli\build\commands\init.js:75:42)
    at D:\NodeJS\node_global\node_modules\selling-lint-cli\build\commands\init.js:148:42
    at Array.forEach (<anonymous>)
    at Command.action (D:\NodeJS\node_global\node_modules\selling-lint-cli\build\commands\init.js:137:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.parseAsync (D:\NodeJS\node_global\node_modules\selling-lint-cli\node_modules\commander\lib\command.js:923:5)
```

**package.json**

```json
{
  "name": "ali-pay-vue",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "axios": "^0.24.0",
    "core-js": "^3.19.2",
    "element-ui": "^2.15.6",
    "js-cookie": "^3.0.1",
    "lodash": "^4.17.21",
    "mockjs": "^1.1.0",
    "swiper": "^5.2.0",
    "vue": "^2.6.14",
    "vue-awesome-swiper": "^4.1.1",
    "vue-fullpage.js": "^0.1.7",
    "vue-router": "^3.5.3",
    "vuex": "^3.6.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-standard": "^5.1.2",
    "babel-eslint": "^10.1.0",
    "commitlint-config-selling": "^0.0.1",
    "eslint": "^6.8.0",
    "eslint-config-selling": "^0.0.1",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.3.1",
    "eslint-plugin-standard": "^4.1.0",
    "eslint-plugin-vue": "^6.2.2",
    "husky": "^7.0.4",
    "sass": "^1.44.0",
    "sass-loader": "^8.0.2",
    "stylelint-config-selling": "^0.0.1",
    "vue-template-compiler": "^2.6.14"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "@vue/standard"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ],
  "lint-staged": {
    "*.{js,jsx,json,ts,tsx,vue}": [
      "eslint --fix",
      "git add"
    ],
    "src/**/*.less": [
      "stylelint --config  ./.stylelintrc --fix",
      "git add"
    ]
  },
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  }
}
```

**Comment by zxyue25** [comment]
好的，我们抽空修复下

**Comment by ziyingjie** [comment]
> 好的，我们抽空修复下

佬 是已经修复了吗

**Comment by robinma** [comment]
我这里没有这个错误

**Comment by robinma** [comment]
可能是cli:src:lib中 conts.ts--depsName的key 的问题，可以尝试把@jd.去掉试一下

**Comment by ziyingjie** [comment]
> 可能是cli:src:lib中 conts.ts--depsName的key 的问题，可以尝试把@jd.去掉试一下

感谢 尝试下先

**Comment by zxyue25** [comment]
已修复，请安装新版本
npm i selling-lint-cli@0.0.4 -g
https://www.npmjs.com/package/selling-lint-cli

**Comment by zxyue25** [comment]
已修复，请安装新版本
npm i selling-lint-cli@0.0.4 -g
https://www.npmjs.com/package/selling-lint-cli
